---
title: "Pacers Player Impact Analysis"
output: html_notebook
---

```{r}
# load libraries 
library(readr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(janitor)
library(zoo)
```


```{r}
# import data 
setwd("/Users/lindseyhornberger/Desktop/My Fun Projects/nba")
nba_player_data <- read.csv("traditional.csv") # player and player_id
nba_team_data <- read.csv("team_traditional.csv") # team and team_id
```


```{r}
# 2025 season data subset
nba_player_2025 <- nba_player_data %>% filter(season == 2025)
```



```{r}
glimpse(nba_player_2025)
summary(nba_player_2025)

colSums(is.na(nba_player_2025)) 
```

Pacers data 
```{r}
pacers_2025 <- nba_player_2025 %>% filter(team == "IND") %>% clean_names()

pacers_2025 <- pacers_2025 %>%
  rename(plus_minus = x,
    fg_pct = fg,
    x3p_pct = x3p,
    ft_pct = ft
  )
pacers_2025 <- pacers_2025 %>%
  mutate(
    efg = ifelse(fga == 0, NA, (fgm + 0.5 * x3pm) / fga),
    ts = ifelse((fga + 0.44 * fta) == 0, NA, pts / (2 * (fga + 0.44 * fta))),
    pm_per_min = ifelse(min == 0, NA, plus_minus / min)
  )


```

Pacers data summary
```{r}
pacers_2025 <- pacers_2025 %>%
  mutate(
    efg = ifelse(fga == 0, NA, (fgm + 0.5 * x3pm) / fga),
    ts = ifelse((fga + 0.44 * fta) == 0, NA, pts / (2 * (fga + 0.44 * fta))),
    pm_per_min = ifelse(minutes == 0, NA, plus_minus / minutes)
  )

player_impact <- pacers_2025 %>%
  group_by(player) %>%
  summarise(
    games = n(),
    mpg = mean(minutes, na.rm = TRUE),
    ppg = mean(pts, na.rm = TRUE),
    apg = mean(ast, na.rm = TRUE),
    rpg = mean(reb, na.rm = TRUE),
    efg = mean(efg, na.rm = TRUE),
    pm_per_min = mean(pm_per_min, na.rm = TRUE)
  ) %>%
  filter(games >= 10, mpg >= 10)
  
player_impact

safe_scale <- function(x) {
  if (sd(x, na.rm = TRUE) == 0) return(rep(0, length(x)))
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
}

player_impact <- player_impact %>%
  mutate(
    impact_score = 
      safe_scale(ppg) * 0.25 +
      safe_scale(apg) * 0.20 +
      safe_scale(rpg) * 0.15 +
      safe_scale(efg) * 0.15 +
      safe_scale(pm_per_min) * 0.25
  ) %>%
  arrange(desc(impact_score))

player_impact
```

Indiana Pacers 2025: Scoring vs On-Court Impact
```{r}
ggplot(player_impact, aes(x = ppg, y = pm_per_min)) +
geom_point(aes(size = impact_score), color = "#FDBB30", alpha = 0.6) +  
 geom_text(aes(label = player), hjust = 1.1, size = ) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  geom_vline(xintercept = mean(player_impact$ppg), 
             linetype = "dashed", color = "gray50") +
  labs(
    title = "Indiana Pacers 2025: Scoring vs On-Court Impact",
    subtitle = "Players in top-right quadrant contribute most to winning",
    x = "Points Per Game",
    y = "+/- Per Minute" ) +
    coord_cartesian(xlim = c(0, 22), ylim = c(-0.2, 0.2)
  ) + 
  theme_minimal()
```


